### ISSUE TITLE
ACXT eats comments text

### ISSUE THREAD

**Issue by noyannus** [Pycea/ACX-tweaks#11]
Comment texts are no longer displayed. Fist thought: Could this be caused by the thread grown too long and hitting a timout? But it's the same with a thread of only 87 comments (Precision of sensory evidence). 

This is what happens:

Freshly reloaded page,  ACXT deactivated: Texts are displayed.
![1  reloaded](https://user-images.githubusercontent.com/6339921/107887260-21f29e00-6f05-11eb-89b6-102464c160a4.png)

ACXT turned on, texts vanish
![2  AXC-T on](https://user-images.githubusercontent.com/6339921/107887010-8f9dca80-6f03-11eb-975c-7e196c9e392c.png)

ACXT turned off again, "Parent" is gone (OK) text still absent
![3  ACX-T off](https://user-images.githubusercontent.com/6339921/107887016-975d6f00-6f03-11eb-8156-e4e3448402da.png)

ACXT turned on again, displays old style
![4  ACXT on again](https://user-images.githubusercontent.com/6339921/107887028-a3e1c780-6f03-11eb-8746-d5254deaea78.png)

And off again, no change
![5  Off again Screenshot](https://user-images.githubusercontent.com/6339921/107887032-a9d7a880-6f03-11eb-8a70-16342d5ef5ad.png)

========

The same with Stylebot deactivated (speeding up rendering, but apparently to no avail)

After reload
![11  reloaded](https://user-images.githubusercontent.com/6339921/107887107-fc18c980-6f03-11eb-9292-b937b8b15d02.png)

ACXT on
![12  ACXT on](https://user-images.githubusercontent.com/6339921/107887054-c673e080-6f03-11eb-841a-69319266a69c.png)

ACXT off
![13  ACXT off](https://user-images.githubusercontent.com/6339921/107887064-d095df00-6f03-11eb-8c5a-1703ed959ba6.png)

ACXT ON
![14  ACXT ON](https://user-images.githubusercontent.com/6339921/107887082-e0adbe80-6f03-11eb-9826-97104f5a932e.png)

ETA: Deep nesting is probably not the cause
![Screenshot](https://user-images.githubusercontent.com/6339921/107887414-384d2980-6f06-11eb-853a-150b130e4c2e.png)

**Comment by Pycea** [comment]
Known issue, should be fixed in 0.14. (Also include what version you're on when reporting a bug, thanks.)
