### ISSUE TITLE
`~new~` markers on new comments are not ctrl-f-able

### ISSUE THREAD

**Issue by chrisjbillington** [Pycea/ACX-tweaks#12]
Thanks for the extension!

In Chrome at least, the `~new~` markers on new comments can't be searched for with ctrl-f. Perhaps they are images and not text? Back on SSC I caught up on new comments with ctrl-f, which is no longer possible on ACX. It would be good if it was.

**Comment by Pycea** [comment]
Done in 0.15, though you may also find the keyboard shortcuts helpful.

**Comment by chrisjbillington** [comment]
Thanks!
