### ISSUE TITLE
Clicking Parent link not remembered in browsing history

### ISSUE THREAD

**Issue by 1024000** [Pycea/ACX-tweaks#13]
If you click a Parent link, it doesn't get into the browsing history, so you can't use the Back button to go back to the previous location. It would be nice to be able to do that. (I'm using Firefox.)

**Comment by Pycea** [comment]
Version 0.17 is coming Soon(tm). When it does, there will be an option under Advanced called "Custom onStart JS". Paste this string there:

```
$(document).on("click", ".comment-actions > span:nth-child(1)", function() {
    let comment = $(this).closest(".comment");
    let parentComment = $(comment).parent().closest(".comment");
    if (parentComment.length > 0) {
        window.location.hash = getCommentId(parentComment[0]);
    }
});
```
