### ISSUE TITLE
More obvious styling for new comments

### ISSUE THREAD

**Issue by bakkot** [Pycea/ACX-tweaks#19]
I find the `~new~` text a little hard to spot; that was always intended more for C-F than as a visual marker. When I was messing around with making a similar thing just now, before I saw your extension, I highlighted the entire left bar (`width: 3px; background-color: #5a5;`):

<img width="734" alt="Screen Shot 2022-05-04 at 6 28 50 PM" src="https://user-images.githubusercontent.com/1653598/166852627-2116eea4-947c-4448-b571-c83eab5c72a1.png">

Also you should have a screenshot in the store which demonstrates the new comment highlighting. The options page is neat but is not the important part of the extension.

**Comment by Pycea** [comment]
The `~new~` text should be orange, I'm not sure why it's not in your case.

I've tried to add classes to things to make them easier to customize though. (see https://github.com/Pycea/ACX-tweaks/wiki/Customization)

New comments have the class `new-comment`, so you could implement your green bar with something like

```
.new-comment > .comment-list-collapser .comment-list-collapser-line {
    width: 3px !important;
    background-color: #5a5 !important;
}
```

(There's currently an issue where changing the new tag color doesn't work. Version 0.24 is currently working its way toward approval and should fix it.)

**Comment by bakkot** [comment]
Sorry, to be clear, that's a screenshot from when I was messing around with things locally before I found your extension.
