### ISSUE TITLE
Collapsing comments no longer works

### ISSUE THREAD

**Issue by telotortium** [Pycea/ACX-tweaks#20]
See <img width="748" alt="Screen Shot 2022-06-13 at 8 07 22 AM" src="https://user-images.githubusercontent.com/1755789/173385095-1f87b9f9-cf57-44bd-8d4e-ff4aea1d31ff.png">.

The gray bars to collapse comments are removed after the page fully loads. I've been seeing this for about a month now.

**Comment by Pycea** [comment]
I'm having trouble replicating this. Can you tell me what browser/OS you're on? And also show what options you're using for good measure? Thanks.

**Comment by Pycea** [comment]
I've removed everything that messes with the collapse bars, so hopefully this isn't an issue anymore.
