### ISSUE TITLE
[suggestion] Margin width set by user

### ISSUE THREAD

**Issue by noyannus** [Pycea/ACX-tweaks#3]
If we could set the width of the empty margins, we could balance short (better readable) lines against more comments on the screen (better overview of a comment sequence). 

How about something like
```
Left margin: NNN px/%
Right margin: NNN px/%
```

There is so much wasted space.
![Screenshot](https://user-images.githubusercontent.com/6339921/107629250-20557b80-6c62-11eb-82a2-8b876bb8e902.png)

Narrow margins would be very helpful for deeply nested comments.

**Comment by Pycea** [comment]
There's a lot of different stylistic preferences possible, but it's better to do those with a different extension, such as [Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha/related?hl=en-US).

In this case, you can set the margins with the custom CSS

```
/* Width of the post */
.single-post-container > .container {
  width: 1000px;
}

/* Width of the comments */
.comments-page > .container {
  width: 1000px;
}
```

Replace with `1000px` with whatever width you want. Note that if you're using the old styling setting, you'll have to set post width to 50px more than the comment width if you want them to match visually.

**Comment by Pycea** [comment]
I'm going to close the CSS related issues, but leave a comment if there's something else you want to say and I'll reopen them.

**Comment by noyannus** [comment]
Thank you for the heads-up to Stylebot and the explanation. No need to reopen the CSS issues.
