### ISSUE TITLE
[suggestion] Offset for posts marked as "new" set by user

### ISSUE THREAD

**Issue by noyannus** [Pycea/ACX-tweaks#4]
If the user could set the offset of new comments as in the old SSC, that would be great. Eg after a crash, or when one continues reading on a different (not synchronized) device.

A stepwise pseudo-log slider would need less user work and even be better than the old SSC date:
```
Mark as "New" posts since the last                                          # menu entry
10 min, 20 min, 30 min, 45 min, 1 hr, 1 1/2 hr, 2 hr, … 1 d, 2 d, 3 d, …    # submenu, vertical slider 
```
Up to 1 week old, after that a thread is usually completely dead.

**Comment by Pycea** [comment]
Can you open a separate issue for the custom string? It helps to have just one issue per feature. Thanks.

**Comment by noyannus** [comment]
Done, also for background colour. I've deleted the new issue material from this OP.

**Comment by Pycea** [comment]
Added an option for this. Setting the "New comment time range" option forces all comments in the last <time> to be shown as new. Added in v0.12.

**Comment by noyannus** [comment]
Already enjoying it. Great to find the new stuff missed in the last hours. :-) Thanks!
