### ISSUE TITLE
[suggestion] Button/link to jump to next "new" post

### ISSUE THREAD

**Issue by noyannus** [Pycea/ACX-tweaks#5]
An additional button at the end of each post (in the line that now is "Reply  Parent" or "Reply  Top") to jump to the next comment below that is marked as "New" would eliminate some searching keystrokes. "Beware of small nuisances." :-)

**Comment by Pycea** [comment]
Added a feature to set keyboard shortcuts to go to the previous/next unread comment. I hope this suffices.

**Comment by noyannus** [comment]
Even better. Thanks!
