### ISSUE TITLE
[suggestion] Mark new posts with different background colour

### ISSUE THREAD

**Issue by noyannus** [Pycea/ACX-tweaks#6]
A nice feature would be if new post were optionally marked with a different background:

```
Mark new posts with
  [ ] Background colour
 ```

**Comment by Pycea** [comment]
New comments are given the class `.new-comment`, so you can use an extension like [Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha?hl=en-US) to style them however you want.

For changing the background color, you can do something like this:

```
.new-comment .comment-content {
    background: #e67e2240;
}
```

If you're using the old styling, you'll have to do this instead:
```
.new-comment .comment-content td:nth-child(2) {
    background: #e67e2240;
}
```

**Comment by noyannus** [comment]
Thanks for the explanation!
This works for me on Firefox (the colors still need tweaking):
```
/* BACKGROUND FOR NEW COMMENT */
/* uncomment only one */

/* for ACX style  */
/*.new-comment.comment-content.new-comment {
  background-color: #eeeeee;
}*/

/* for old SSC style */
.new-comment td:nth-child(2){
  background-color: #e67e2240;
}
```
