### ISSUE TITLE
[suggestion] Let user define the string that marks new posts

### ISSUE THREAD

**Issue by noyannus** [Pycea/ACX-tweaks#7]
A user definable string would allow individual preferences, like visually strong ("❗️❗️❗️", "⚠️", "🔵"), quick to type for in-page search ("asdf", "ggg"), or nostalgia ("~new~").

```
Mark new posts with
  [ ] String [____]          # added to the the datetime line
```

**Comment by Pycea** [comment]
Another [Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha/related?hl=en-US) fix.

The new post text is just an empty span with class `.new-tag`, so you can change it however you want. For example, to make it red text that says "test", do:
```
.new-tag:after {
  color: red;
  content: "test";
}
```
The `content` attribute will be the text that is shown. Any other styling can also be applied.

**Comment by noyannus** [comment]
THanks!

To also replace "~new~" this works OK on Firefox (appearance needs refinement):
```
/* NEW COMMENTS MARKER */
/* replaces "~new~" */
.new-tag {
  visibility: hidden;
  width: 0px
}
.new-tag:before {
  content: "  ••••••••••••••  ";
  margin-left: 12px;
  color: #DDFF00;
  background-color: #FF0000;
  visibility: visible;
}

```

**Comment by Pycea** [comment]
Hm, if you have v0.11 you should only need

```
.new-tag:after {
  color: #DDFF00;
  background-color: #FF0000;
  content: "  ••••••••••••••  ";
}
```

It's available in the stores now and also on the release page.

**Comment by noyannus** [comment]
The "\~new\~" remained visible (a Firefox issue?), hence the `visibility` hack. Didn't think deeper about it, it's adapted Stackoverflow copypasta.` Newtag:before` instead of `…:after` moves the invisible "\~new\~" to the right of the inserted content. Somehow simply replacing that string didn't work.

**Comment by Pycea** [comment]
Hm, that's odd. It works for me on Firefox. Which version are you running? Are you using Stylebot or a different css injector? Does adding `!important` work?

```
.new-tag:after {
  color: #DDFF00 !important;
  background-color: #FF0000 !important;
  content: "  ••••••••••••••  " !important;
}
```

**Comment by noyannus** [comment]
FF 86.0b9 64 bit on macOS 10.14.6
Stylebot 3.0.7
!important; makes no difference:

![Screenshot](https://user-images.githubusercontent.com/6339921/107879672-89dfbf00-6eda-11eb-8427-114593c3978d.png)

I grabbed the idea [here](https://stackoverflow.com/questions/7896402/how-can-i-replace-text-with-css).

**Comment by Pycea** [comment]
Hm, still works for me on the FF beta on macos (different version, but if that's the issue I'll get a hat and eat it). It's also odd that the new text is before the date, is that what it looks like without any stylebot css? It still does that even if you have just that rule in stylebot?

Can you try getting v0.12 from the store? It should be out now.

If the new version is still broken, can you do this:
Inspect element on the new text. There should be an expand there, with `::after` inside. Select that, and take a screenshot of the html and css rules, there should be a two rules for `.new-tag::after`
![image](https://user-images.githubusercontent.com/78026493/107880377-2e3e1300-6e93-11eb-9784-87338349d7c4.png)

Thanks. (Sorry if you already know how to do all that)

**Comment by noyannus** [comment]
Now it works as you expect. 

![Screenshot](https://user-images.githubusercontent.com/6339921/107882295-bf8ba480-6ee8-11eb-8c2b-baf9991f0bf2.png)

I've made several changes at once, so not sure what made the difference:


- AXC Tweaks v0.12
- ACX Tweaks via Mozilla store, not from GitHub Releases page. 
- Deleted the Stylebot style that was set globally for `astralcodexten.substack.com` (but that had no effect whatsoever before and had the pre-`!important` code; a different issue). 

`!important` is only necessary for `content:`:

![Screenshot 2](https://user-images.githubusercontent.com/6339921/107882284-b4387900-6ee8-11eb-91be-4b2ad027c665.png)

**Comment by Pycea** [comment]
I've changed things a little, if you want a custom marker you can use:

```
.new-tag-text {
  display: none;
}

.new-tag-css:after {
    content: "<text>";
    color: red;
}
```
