### ISSUE TITLE
Full datetime displayed after turned off

### ISSUE THREAD

**Issue by noyannus** [Pycea/ACX-tweaks#8]
Turn on long datetime and off again, it remains visible.

![Screenshot 1](https://user-images.githubusercontent.com/6339921/107876573-04064880-6ec7-11eb-862e-186168842834.png)

(Ignore the aesthetics, please!)

**Comment by Pycea** [comment]
Works for me with v0.11. Does the issue persist if you refresh?

Also thanks for the bug testing.

**Comment by noyannus** [comment]
Restarted FF (suddenly dragging an image into this very field didn't work anymore, this FF is on the *beta* update channel), the issue persist with *only the new* comments. I don't remember if that was the case before, or if all comments were affected.

![Screenshot](https://user-images.githubusercontent.com/6339921/107880558-e09bc780-6edf-11eb-8169-e1c7ef12c065.png)

> Also thanks for the bug testing.

Giving back to the web. Thanks for writing the tweaks in the first place.

**Comment by Pycea** [comment]
Ah yes. For, uh, complicated reasons, the exact time isn't shown for dynamically loaded comments. (Basically, when you load the page, it has a list of the exact times for all the current comments, but there's no clean way to get the time for new comments.) I may try to fix this eventually, but I'll make a new issue for that.

**Comment by noyannus** [comment]
OK. Thanks for looking into it.
