### ISSUE TITLE
Keyboard shortcuts are passed on to Firefox' search field

### ISSUE THREAD

**Issue by noyannus** [Pycea/ACX-tweaks#9]
… so after the first `u` FF searches for `uu`. Disabling search on type would turn off a FF feature too useful to go without.

**Comment by Pycea** [comment]
I'm not sure what you mean by this. Is `u` a keyboard shortcut for something?

If one of the shortcuts does conflict with a browser feature, it's probably better in general to just change the extension shortcut, even if it is possible to prevent them from being passed on.

**Comment by noyannus** [comment]
`U` set for previous comment. 
![Screenshot 1](https://user-images.githubusercontent.com/6339921/107880740-17bea880-6ee1-11eb-89c3-5149dce208c9.png)

**Comment by Pycea** [comment]
Huh, did not know about that feature. Looks like it's easy enough to fix. (You won't be able to search for anything starting with u, but you can always just change the shortcut.) Fix will be out shortly in 0.13.

**Comment by noyannus** [comment]
Thanks!
